import StyleDictionary from 'style-dictionary'

StyleDictionary.registerTransform({
  name: 'name/ds-kebab',
  type: 'name',
  transform: ({ path }) =>
    path
      .join('-')
      .replace(/([a-z])([A-Z])/g, '$1-$2')
      .replace(/-+/g, '-')
      .toLowerCase(),
})

StyleDictionary.registerTransformGroup({
  name: 'css/ds',
  transforms: ['name/ds-kebab', 'color/css'],
})

const sd = new StyleDictionary({
  source: [
    'tokens/color/primitive.json',
    'tokens/color/semantic.json',
    'tokens/shadow.json',
    'tokens/typography.json',
    'tokens/spacing.json',
    'tokens/radius.json',
  ],
  platforms: {
    css: {
      transformGroup: 'css/ds',
      buildPath: 'css/',
      files: [
        {
          destination: 'variables.css',
          format: 'css/variables',
          options: {
            selector: ':root',
            outputReferences: true,
            fileHeader: () => [
              'Design System — CSS Custom Properties',
              'Generated by Style Dictionary. Do not edit manually.',
              'Source: tokens/   Build: bun run build',
            ],
          },
        },
      ],
    },
  },
})

await sd.buildAllPlatforms()
console.log('css/variables.css generated')
